appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XL0x35BqBHhqz673YHyRamGhtu8Pr46SJ1mPqtgKGyFIRJlP3r6cNLJIOV4Nn+OWrJQa50VJIKPvbASNkLZjtUDRuQv5cr/K1XIV2FxwEPtIuHwp5Ot/4tq3IK/YVZMCWav+5hpn2D2djG8MYC0NG+lbokPGOpvVKJmts6GvO9eAth4SAd3yppYr1sHx1AROMzgvmLsXVkEMjauFu+cFrPPkh6YiFkYStSbrarmTFl2vN0xknOUmS7J3S5wLHb6I7W3dA7tFkhVwG8PW+sRQprXGKyDTD6MRDYZb3ecuE+/LnVgeTXKcNdCiF+8HJuepqNYGyVGZNyYCNj0vgeUDEdp39r40pTkMbNqLY8ASX6QsiPuLO+K8ZB7im7/AtKuc7UnoC5/6fUfdmmmCpgAkPa8XmKXSYKITd2JQzw/Op0wD8gtBr15k9rFuoXPCjs666AN9dy87zuUrUEuso2eCBw8xZBFNWhHXx8YgxT7Rmgd6rNfORW/HPrWgNEuAB3f+PuYp6ZmWgEaT/WT9DeB+DBiV3e4PVRj2VUbTyQz5E/XuyYEAgZN1wLvWWSIPUcHy8raJvdYGqRuJwTB/WBZEttzbn71+tKJPpVJqvn3xrhbz+KZ7As7RZnxx6RiayLShN/r4QimGXMy6hZh+DXmq3FcNk1WMuYdvk8kXFAHUmOI=
conda_forge_output_validation: false
